#12 schedule
volsu-infosystem/service-schedule pull request #20
Opened 2021-02-17 16:43 UTC by DanielTenebris

2021-02-17 16:53 UTC, DVegasa requested changes

2021-02-17 16:53 UTC, DVegasa commented on backend/src/schedule/enums/importanceStatus.enum.ts
> +  hight = 'hight',
typo

2021-02-17 16:53 UTC, DVegasa commented on backend/src/schedule/enums/lessonType.enum.ts
> +}
Не ограничивай так сильно. Могут быть ещё семинары, праздники, подготовки к экзаменам и куча другой фигни

2021-02-17 16:55 UTC, DVegasa commented on backend/src/schedule/enums/periodicity.enum.ts
> +  once = 'one',
Возможно, once = 'once' будет лучше по неймингу

2021-02-17 16:57 UTC, niqitosiq requested changes
Поправочки

2021-02-17 16:57 UTC, niqitosiq commented on .env
> +TARGET=production
это не так работает. 
Чтобы у тебя продакшн развернулся, нужно делать docker-compose для билд сборки. Чуть позже сделаю, а пока это лучше убрать

2021-02-17 16:57 UTC, niqitosiq commented on backend/Dockerfile
> +EXPOSE 3000
Если уж и прокидываешь порты, то прокидывай их в development, иначе бекдур для прода

2021-02-17 16:57 UTC, niqitosiq commented on backend/src/schedule/lesson.service.ts
> +      loadRelationIds: true,
Вот вместо этого указывай `relations: ["discipline", "professor", "room"]`, и убирай свою "карусель", orm всё автоматом подтянет https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#basic-options

2021-02-17 16:57 UTC, niqitosiq commented on backend/src/schedule/schedule.service.ts
> +    const lessonsListResponse = await Promise.all(
вот этот весь лишний парсинг убрать в соответствии с коментом выше можно

2021-02-17 17:08 UTC, niqitosiq commented
а ваще круто написано, мне нравится

2021-02-19 07:49 UTC, DanielTenebris commented on backend/src/schedule/enums/lessonType.enum.ts
> +}
Если будут - введем.

2021-02-19 07:49 UTC, DanielTenebris commented on backend/src/schedule/enums/importanceStatus.enum.ts
> +  hight = 'hight',
А как нужно?

2021-02-19 07:50 UTC, DanielTenebris commented on backend/src/schedule/lesson.service.ts
> +      loadRelationIds: true,
Спасибо, посмотрю

2021-02-19 13:19 UTC, DVegasa commented on backend/src/schedule/enums/importanceStatus.enum.ts
> +  hight = 'hight',
> А как нужно?

high

2021-02-19 16:24 UTC, DanielTenebris commented on backend/src/schedule/enums/importanceStatus.enum.ts
> +  hight = 'hight',
🤡 Точно. Исправил.

2021-02-19 16:24 UTC, DanielTenebris commented on backend/src/schedule/enums/periodicity.enum.ts
> +  once = 'one',
Верно.

2021-02-20 13:07 UTC, niqitosiq requested changes

2021-02-20 13:07 UTC, niqitosiq commented on .env
> +TARGET=production
Вот это я удалял до форспуша

2021-02-20 13:07 UTC, niqitosiq commented on backend/Dockerfile
> +EXPOSE 3000
и это

2021-02-21 06:46 UTC, DVegasa approved these changes
Ожидай подтверждения от Никиты

2021-02-22 18:14 UTC, niqitosiq approved these changes

2021-02-22 18:15 UTC, merged